###get all techmoms local
GET http://localhost:5000/techmoms

###get all techmoms heroku
GET https://cse341-techmoms.herokuapp.com/techmoms HTTP/1.1

###create contact
POST http://localhost:5000/techmoms HTTP/1.1
content-type: application/json

{
    "firstName": "Hallie",
    "lastName": "Berry",
    "city": "Brooklyn",
    "state": "NY",
    "title": "Super Boss",
    "seekingJobTitle": "Technical Recruiter",
    "headline": "I am the Super Boss",
}

